Fix tf.py_func typo
Currently unit tests on master fail with [`AttributeError: module 'tensorflow' has no attribute 'py_function'`](https://travis-ci.org/tensorflow/tensor2tensor/jobs/477996581#L2440).

Unfortunately this is hard to spot since Python 2 builds are failing due to #1319 and Python 3 builds are cluttered with `inspect.getargspec()` deprecation warnings from tensorflow.