Fix broken universal_transformer_teeny
universal_transformer_teeny() always fails with 

```
raise ValueError('Hyperparameter name is reserved: %s' % name)
ValueError: Hyperparameter name is reserved: num_rec_steps
```

This is because universal_transformer_teeny does

transformer_teeny => hparams.num_rec_steps = 2 => update_hparams_for_universal_transformer => tries to add num_rec_steps to hparams.

num_rec_steps is already in hparams, so it fails.  

Deleting num_rec_steps from transformer_teeny seemed like the most logical solution here.